name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install IVerilog
      run: sudo apt-get install iverilog
    - name: Install GHC Dependencies
      run: |
           sudo apt-get update
           sudo apt-get install ghc
           sudo apt-get install libghc-regex-compat-dev libghc-syb-dev libghc-old-time-dev libghc-split-dev
           sudo apt-get install autoconf gperf
           sudo apt-get install tcl-dev
           sudo apt-get install flex bison
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Cache BSV
      id:   cache-bsc
      uses: actions/cache@v2
      with:
        path: bsc
        key: ubuntu-bsc
    - name: Install BSV
      if: steps.cache-bsc.outputs.cache-hit != 'true'
      run: 
           git clone --recursive --branch 2021.07 https://github.com/B-Lang-org/bsc
           pushd bsc
           make install-src
           popd
    - name: Build Libs
      env:
        BLUESPECDIR: ${{github.workspace}}/bsc
      run: |
        export BLUESPECDIR=${{env.BLUESPECDIR}}
        export PATH="$PATH":"$BLUESPECDIR"/inst/bin
        echo "$BLUESPECDIR"
        echo "$PATH"
        make
    - name: Run tests
      env:
        BLUESPECDIR: ${{github.workspace}}/bsc
      run: |
        export BLUESPECDIR=${{env.BLUESPECDIR}}
        export PATH="$PATH":"$BLUESPECDIR"/inst/bin
        sbt test








