name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install IVerilog
      run: sudo apt-get install iverilog
    - name: Install GHC Dependencies
      run: |
           sudo apt-get update
           sudo apt-get install ghc
           sudo apt-get install libghc-regex-compat-dev libghc-syb-dev libghc-old-time-dev libghc-split-dev
           sudo apt-get install autoconf gperf
           sudo apt-get install tcl-dev
           sudo apt-get install flex bison
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Cache BSV
      id:   cache-bsc
      uses: actions/cache@v2
      with:
        path: bsc
        key: ubuntu-bsc
    - name: Install BSV
      id: install-bsv
      run: |
        wget https://github.com/B-Lang-org/bsc/releases/download/2021.07/bsc-2021.07-ubuntu-18.04.tar.gz
        tar -xvf bsc-2021.07-ubuntu-18.04.tar.gz
        mv bsc-2021.07-ubuntu-18.04 bsc
    - name: Build Libs
      env:
        BLUESPECDIR: ${{github.workspace}}/bsc
      run: |
        export BLUESPECDIR=${{env.BLUESPECDIR}}
        export PATH="$PATH":"$BLUESPECDIR"/bin
        echo "$BLUESPECDIR"
        echo "$PATH"
        make
    - name: Run tests
      env:
        BLUESPECDIR: ${{github.workspace}}/bsc
      run: |
        export BLUESPECDIR=${{env.BLUESPECDIR}}
        export PATH="$PATH":"$BLUESPECDIR"/bin
        sbt test








